# Generated by Django 3.2.15 on 2022-09-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
    ]
